parametrize model name and engine

diff --git a/libs/infinity_emb/Dockerfile.flash b/libs/infinity_emb/Dockerfile.flash
--- a/libs/infinity_emb/Dockerfile.flash
+++ b/libs/infinity_emb/Dockerfile.flash
@@ -12,5 +12,13 @@ RUN pip install flash_attn
 
 RUN pip install infinity-emb[all]
 
-RUN infinity_emb v2 --model-id dunzhang/stella_en_1.5B_v5 --engine torch --preload-only || [ $? -eq 3 ]
+ARG MODEL_NAME
+RUN if [ -z "${MODEL_NAME}" ]; then echo "Error: Build argument MODEL_NAME not set." && exit 1; fi
+ARG ENGINE
+RUN if [ -z "${ENGINE}" ]; then echo "Error: Build argument ENGINE not set." && exit 1; fi
+ARG EXTRA_PACKAGES
+RUN if [ -n "${EXTRA_PACKAGES}" ]; then pip install --no-cache-dir ${EXTRA_PACKAGES} ; fi
+
+
+RUN infinity_emb v2 --model-id $MODEL_NAME --engine $ENGINE --preload-only || [ $? -eq 3 ]
 ENTRYPOINT ["infinity_emb"]
